version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    networks:
      - my-network
    ports:
      - "50051:50051"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    networks:
      - my-network
    ports:
      - "8501:8501"

networks:
  my-network:
    driver: bridge
